from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_4code', models.CharField(max_length=4, verbose_name='机场四字代码')),
                ('sqc', models.CharField(db_index=True, max_length=50, verbose_name='SQC标识')),
                ('whole_validity_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='整体预报有效期')),
                ('taf_observation_time', models.BigIntegerField(blank=True, null=True, verbose_name='发布时间')),
                ('taf_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='taf报文类型')),
                ('taf_content', models.TextField(blank=True, null=True, verbose_name='taf原文')),
                ('subject_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='主预报起始时间')),
                ('subject_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='主预报截至时间')),
                ('subject_content', models.TextField(blank=True, null=True, verbose_name='主预报原文')),
                ('subject_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='主预报告警等级')),
                ('subject_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='主预报风速(m/s)')),
                ('subject_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='主预报阵风(m/s)')),
                ('subject_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='主预报风组告警')),
                ('subject_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='主预报能见度(m)')),
                ('subject_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='主预报能见度告警')),
                ('subject_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='主预报天气现象1')),
                ('subject_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='主预报天气现象2')),
                ('subject_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='主预报天气现象3')),
                ('subject_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='主预报天气现象4')),
                ('subject_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='主预报天气现象5')),
                ('subject_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='主预报天气现象告警')),
                ('subject_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='主预报最低云高')),
                ('subject_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='主预报云组告警')),
                ('subject_max_temp1', models.CharField(blank=True, max_length=10, null=True, verbose_name='第1个最高温度')),
                ('subject_max_temp1_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='第1个最高温度所在时间')),
                ('subject_max_temp1_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='第1个最高温度告警等级')),
                ('subject_max_temp2', models.CharField(blank=True, max_length=10, null=True, verbose_name='第2个最高温度')),
                ('subject_max_temp2_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='第2个最高温度所在时间')),
                ('subject_max_temp2_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='第2个最高温度告警等级')),
                ('subject_min_temp1', models.CharField(blank=True, max_length=10, null=True, verbose_name='第1个最低温度')),
                ('subject_min_temp1_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='第1个最低温度所在时间')),
                ('subject_min_temp1_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='第1个最低温度告警等级')),
                ('subject_min_temp2', models.CharField(blank=True, max_length=10, null=True, verbose_name='第2个最低温度')),
                ('subject_min_temp2_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='第2个最低温度所在时间')),
                ('subject_min_temp2_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='第2个最低温度告警等级')),
                ('change_1_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组1的类型')),
                ('change_1_content_all', models.TextField(blank=True, null=True, verbose_name='变化组1的原文')),
                ('change_1_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组1的告警等级')),
                ('change_1_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组1的起始时间')),
                ('change_1_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组1的截止时间')),
                ('change_1_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组1风速(m/s)')),
                ('change_1_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组1阵风(m/s)')),
                ('change_1_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组1风组告警')),
                ('change_1_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组1能见度(m)')),
                ('change_1_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组1能见度告警')),
                ('change_1_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组1天气现象1')),
                ('change_1_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组1天气现象2')),
                ('change_1_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组1天气现象3')),
                ('change_1_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组1天气现象4')),
                ('change_1_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组1天气现象5')),
                ('change_1_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组1天气现象告警')),
                ('change_1_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组1最低云高')),
                ('change_1_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组1云组告警')),
                ('change_2_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组2的类型')),
                ('change_2_content_all', models.TextField(blank=True, null=True, verbose_name='变化组2的原文')),
                ('change_2_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组2的告警等级')),
                ('change_2_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组2的起始时间')),
                ('change_2_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组2的截止时间')),
                ('change_2_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组2风速(m/s)')),
                ('change_2_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组2阵风(m/s)')),
                ('change_2_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组2风组告警')),
                ('change_2_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组2能见度(m)')),
                ('change_2_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组2能见度告警')),
                ('change_2_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组2天气现象1')),
                ('change_2_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组2天气现象2')),
                ('change_2_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组2天气现象3')),
                ('change_2_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组2天气现象4')),
                ('change_2_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组2天气现象5')),
                ('change_2_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组2天气现象告警')),
                ('change_2_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组2最低云高')),
                ('change_2_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组2云组告警')),
                ('change_3_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组3的类型')),
                ('change_3_content_all', models.TextField(blank=True, null=True, verbose_name='变化组3的原文')),
                ('change_3_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组3的告警等级')),
                ('change_3_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组3的起始时间')),
                ('change_3_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组3的截止时间')),
                ('change_3_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组3风速(m/s)')),
                ('change_3_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组3阵风(m/s)')),
                ('change_3_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组3风组告警')),
                ('change_3_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组3能见度(m)')),
                ('change_3_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组3能见度告警')),
                ('change_3_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组3天气现象1')),
                ('change_3_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组3天气现象2')),
                ('change_3_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组3天气现象3')),
                ('change_3_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组3天气现象4')),
                ('change_3_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组3天气现象5')),
                ('change_3_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组3天气现象告警')),
                ('change_3_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组3最低云高')),
                ('change_3_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组3云组告警')),
                ('change_4_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组4的类型')),
                ('change_4_content_all', models.TextField(blank=True, null=True, verbose_name='变化组4的原文')),
                ('change_4_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组4的告警等级')),
                ('change_4_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组4的起始时间')),
                ('change_4_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组4的截止时间')),
                ('change_4_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组4风速(m/s)')),
                ('change_4_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组4阵风(m/s)')),
                ('change_4_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组4风组告警')),
                ('change_4_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组4能见度(m)')),
                ('change_4_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组4能见度告警')),
                ('change_4_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组4天气现象1')),
                ('change_4_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组4天气现象2')),
                ('change_4_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组4天气现象3')),
                ('change_4_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组4天气现象4')),
                ('change_4_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组4天气现象5')),
                ('change_4_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组4天气现象告警')),
                ('change_4_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组4最低云高')),
                ('change_4_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组4云组告警')),
                ('change_5_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组5的类型')),
                ('change_5_content_all', models.TextField(blank=True, null=True, verbose_name='变化组5的原文')),
                ('change_5_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组5的告警等级')),
                ('change_5_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组5的起始时间')),
                ('change_5_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组5的截止时间')),
                ('change_5_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组5风速(m/s)')),
                ('change_5_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组5阵风(m/s)')),
                ('change_5_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组5风组告警')),
                ('change_5_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组5能见度(m)')),
                ('change_5_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组5能见度告警')),
                ('change_5_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组5天气现象1')),
                ('change_5_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组5天气现象2')),
                ('change_5_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组5天气现象3')),
                ('change_5_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组5天气现象4')),
                ('change_5_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组5天气现象5')),
                ('change_5_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组5天气现象告警')),
                ('change_5_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组5最低云高')),
                ('change_5_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组5云组告警')),
                ('change_6_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组6的类型')),
                ('change_6_content_all', models.TextField(blank=True, null=True, verbose_name='变化组6的原文')),
                ('change_6_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组6的告警等级')),
                ('change_6_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组6的起始时间')),
                ('change_6_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组6的截止时间')),
                ('change_6_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组6风速(m/s)')),
                ('change_6_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组6阵风(m/s)')),
                ('change_6_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组6风组告警')),
                ('change_6_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组6能见度(m)')),
                ('change_6_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组6能见度告警')),
                ('change_6_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组6天气现象1')),
                ('change_6_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组6天气现象2')),
                ('change_6_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组6天气现象3')),
                ('change_6_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组6天气现象4')),
                ('change_6_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组6天气现象5')),
                ('change_6_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组6天气现象告警')),
                ('change_6_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组6最低云高')),
                ('change_6_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组6云组告警')),
                ('change_7_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组7的类型')),
                ('change_7_content_all', models.TextField(blank=True, null=True, verbose_name='变化组7的原文')),
                ('change_7_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组7的告警等级')),
                ('change_7_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组7的起始时间')),
                ('change_7_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组7的截止时间')),
                ('change_7_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组7风速(m/s)')),
                ('change_7_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组7阵风(m/s)')),
                ('change_7_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组7风组告警')),
                ('change_7_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组7能见度(m)')),
                ('change_7_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组7能见度告警')),
                ('change_7_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组7天气现象1')),
                ('change_7_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组7天气现象2')),
                ('change_7_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组7天气现象3')),
                ('change_7_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组7天气现象4')),
                ('change_7_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组7天气现象5')),
                ('change_7_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组7天气现象告警')),
                ('change_7_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组7最低云高')),
                ('change_7_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组7云组告警')),
                ('change_8_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组8的类型')),
                ('change_8_content_all', models.TextField(blank=True, null=True, verbose_name='变化组8的原文')),
                ('change_8_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组8的告警等级')),
                ('change_8_validity_period_start', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组8的起始时间')),
                ('change_8_validity_period_end', models.CharField(blank=True, max_length=10, null=True, verbose_name='变化组8的截止时间')),
                ('change_8_wind_speed_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组8风速(m/s)')),
                ('change_8_gust_mps', models.IntegerField(blank=True, null=True, verbose_name='变化组8阵风(m/s)')),
                ('change_8_wind_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组8风组告警')),
                ('change_8_visibility_m', models.IntegerField(blank=True, null=True, verbose_name='变化组8能见度(m)')),
                ('change_8_visibility_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组8能见度告警')),
                ('change_8_weather1', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组8天气现象1')),
                ('change_8_weather2', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组8天气现象2')),
                ('change_8_weather3', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组8天气现象3')),
                ('change_8_weather4', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组8天气现象4')),
                ('change_8_weather5', models.CharField(blank=True, max_length=20, null=True, verbose_name='变化组8天气现象5')),
                ('change_8_weather_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组8天气现象告警')),
                ('change_8_cloud_min', models.IntegerField(blank=True, null=True, verbose_name='变化组8最低云高')),
                ('change_8_cloud_warning', models.CharField(blank=True, choices=[('R', '红色'), ('Y', '黄色'), ('G', '绿色'), ('N', '无告警')], max_length=1, null=True, verbose_name='变化组8云组告警')),
                ('amd_or_cor', models.CharField(blank=True, max_length=3, null=True, verbose_name='修正或更正标识')),
                ('error_report', models.TextField(blank=True, null=True, verbose_name='错误报告')),
                ('abnormal_label', models.CharField(blank=True, max_length=20, null=True, verbose_name='异常标签')),
                ('data_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='数据状态')),
                ('import_alert', models.CharField(blank=True, max_length=1, null=True, verbose_name='入库告警标记')),
                ('import_alert_time', models.BigIntegerField(blank=True, null=True, verbose_name='入库告警时间戳')),
                ('import_alert_handle_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='告警处理状态')),
                ('created_at', models.BigIntegerField(verbose_name='创建时间戳（毫秒）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TAF数据',
                'verbose_name_plural': 'TAF数据',
                'db_table': 'taf',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taf',
            index=models.Index(fields=['airport_4code', '-created_at'], name='taf_airport_created_idx'),
        ),
        migrations.AddIndex(
            model_name='taf',
            index=models.Index(fields=['taf_observation_time'], name='taf_obs_time_idx'),
        ),
        migrations.AddIndex(
            model_name='taf',
            index=models.Index(fields=['taf_content'], name='taf_content_idx'),
        ),
        migrations.AddIndex(
            model_name='taf',
            index=models.Index(fields=['whole_validity_period'], name='taf_validity_idx'),
        ),
    ]
