# Generated by Django 6.0.4 on 2026-04-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_create_taf'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taf',
            new_name='taf_airport_044783_idx',
            old_name='taf_airport_created_idx',
        ),
        migrations.RenameIndex(
            model_name='taf',
            new_name='taf_taf_obs_fe7529_idx',
            old_name='taf_obs_time_idx',
        ),
        migrations.RenameIndex(
            model_name='taf',
            new_name='taf_taf_con_b1f7bd_idx',
            old_name='taf_content_idx',
        ),
        migrations.RenameIndex(
            model_name='taf',
            new_name='taf_whole_v_1eefec_idx',
            old_name='taf_validity_idx',
        ),
        migrations.AddField(
            model_name='taf',
            name='handle_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='告警处理状态'),
        ),
        migrations.AlterField(
            model_name='taf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
