# Generated by Django 6.0.4 on 2026-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_add_handle_status_to_taf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taf',
            name='import_alert_handle_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='告警处理时间戳'),
        ),
    ]
