# Generated by Django 5.2.4 on 2025-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportInfoAndAlertThresholds',
            fields=[
                ('airport_4code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='机场四字代码')),
                ('airport_3code', models.CharField(blank=True, max_length=3, null=True, verbose_name='机场三字代码')),
                ('airport_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='机场名称')),
                ('classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='性质')),
                ('area', models.CharField(blank=True, choices=[('华南', '华南'), ('华东', '华东'), ('华北', '华北'), ('东北', '东北'), ('西南', '西南'), ('西北', '西北'), ('港台', '港台'), ('其它', '其它'), ('东亚', '东亚'), ('东南亚', '东南亚'), ('南亚', '南亚'), ('中东', '中东'), ('中/西亚', '中/西亚'), ('欧洲', '欧洲'), ('北美', '北美'), ('南美', '南美'), ('澳洲', '澳洲'), ('非洲', '非洲')], max_length=10, null=True, verbose_name='区域')),
                ('area_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='区号')),
                ('forecast_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='预报电话')),
                ('observation_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='观测电话')),
                ('other_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='其他电话')),
                ('visibility_m_red', models.PositiveIntegerField(default=800, verbose_name='能见度红色告警值')),
                ('visibility_m_yellow', models.PositiveIntegerField(default=1600, verbose_name='能见度黄色告警值')),
                ('visibility_m_green', models.PositiveIntegerField(default=2000, verbose_name='能见度绿色告警值')),
                ('cloud_min_red', models.PositiveIntegerField(default=2, verbose_name='云高红色告警值')),
                ('cloud_min_yellow', models.PositiveIntegerField(default=5, verbose_name='云高黄色告警值')),
                ('cloud_min_green', models.PositiveIntegerField(default=10, verbose_name='云高绿色告警值')),
                ('average_wind_speed_mps_red', models.PositiveIntegerField(default=12, verbose_name='平均风红色告警值')),
                ('average_wind_speed_mps_yellow', models.PositiveIntegerField(default=8, verbose_name='平均风黄色告警值')),
                ('average_wind_speed_mps_green', models.PositiveIntegerField(default=5, verbose_name='平均风绿色告警值')),
                ('gust_mps_red', models.PositiveIntegerField(default=17, verbose_name='阵风红色告警值')),
                ('gust_mps_yellow', models.PositiveIntegerField(default=13, verbose_name='阵风黄色告警值')),
                ('gust_mps_green', models.PositiveIntegerField(default=10, verbose_name='阵风绿色告警值')),
                ('temperature_cold_red', models.IntegerField(default=-30, verbose_name='低温红色告警值')),
                ('temperature_cold_yellow', models.IntegerField(default=-27, verbose_name='低温黄色告警值')),
                ('temperature_cold_green', models.IntegerField(default=-25, verbose_name='低温绿色告警值')),
                ('temperature_hot_red', models.PositiveIntegerField(default=40, verbose_name='高温红色告警值')),
                ('temperature_hot_yellow', models.PositiveIntegerField(default=37, verbose_name='高温黄色告警值')),
                ('temperature_hot_green', models.PositiveIntegerField(default=35, verbose_name='高温绿色告警值')),
                ('Inherited_label', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, verbose_name='继承标签')),
                ('extraInfo1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('extraInfo2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('extraInfo3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('extraInfo4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('extraInfo5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('extraInfo6', models.TextField(blank=True, null=True, verbose_name='预留字段6')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机场信息和告警阈值',
                'verbose_name_plural': '机场信息和告警阈值',
                'db_table': 'airport_info_and_alert_thresholds',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_code', models.CharField(max_length=2, unique=True, verbose_name='航空公司二字代码')),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='航空公司名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '航空公司',
                'verbose_name_plural': '航空公司',
                'db_table': 'carrier',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('data_retention', '数据保留配置'), ('auto_refresh', '自动刷新配置'), ('data_source', '数据源配置')], max_length=20, verbose_name='配置类型')),
                ('config_key', models.CharField(max_length=50, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
                'unique_together': {('config_type', 'config_key')},
            },
        ),
        migrations.CreateModel(
            name='WeatherAlertLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=20, verbose_name='天气现象代码')),
                ('alert_level', models.CharField(choices=[('R', '红色告警'), ('Y', '黄色告警'), ('G', '绿色告警')], max_length=1, verbose_name='告警等级')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '天气现象告警等级',
                'verbose_name_plural': '天气现象告警等级',
                'db_table': 'weather_alert_levels',
                'unique_together': {('weather', 'alert_level')},
            },
        ),
    ]
