# Generated by Django 5.2.4 on 2025-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportinfoandalertthresholds',
            name='area',
            field=models.CharField(blank=True, choices=[('华中', '华中'), ('华南', '华南'), ('华东', '华东'), ('华北', '华北'), ('东北', '东北'), ('西南', '西南'), ('西北', '西北'), ('港台', '港台'), ('其它', '其它'), ('东亚', '东亚'), ('东南亚', '东南亚'), ('南亚', '南亚'), ('中东', '中东'), ('中/西亚', '中/西亚'), ('欧洲', '欧洲'), ('北美', '北美'), ('南美', '南美'), ('澳洲', '澳洲'), ('非洲', '非洲')], max_length=10, null=True, verbose_name='区域'),
        ),
    ]
