# Generated by Django 5.2.4 on 2025-09-01 02:39

from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    """将原表数据拆分到两个新表中"""
    AirportInfoAndAlertThresholds = apps.get_model('core', 'AirportInfoAndAlertThresholds')
    AirportInfo = apps.get_model('core', 'AirportInfo')
    AirportAlertThresholds = apps.get_model('core', 'AirportAlertThresholds')
    
    # 创建告警阈值表，只保存default行
    default_data = AirportInfoAndAlertThresholds.objects.filter(airport_4code='default').first()
    if default_data:
        AirportAlertThresholds.objects.create(
            airport_4code='default',
            visibility_m_red=default_data.visibility_m_red,
            visibility_m_yellow=default_data.visibility_m_yellow,
            visibility_m_green=default_data.visibility_m_green,
            cloud_min_red=default_data.cloud_min_red,
            cloud_min_yellow=default_data.cloud_min_yellow,
            cloud_min_green=default_data.cloud_min_green,
            average_wind_speed_mps_red=default_data.average_wind_speed_mps_red,
            average_wind_speed_mps_yellow=default_data.average_wind_speed_mps_yellow,
            average_wind_speed_mps_green=default_data.average_wind_speed_mps_green,
            gust_mps_red=default_data.gust_mps_red,
            gust_mps_yellow=default_data.gust_mps_yellow,
            gust_mps_green=default_data.gust_mps_green,
            temperature_cold_red=default_data.temperature_cold_red,
            temperature_cold_yellow=default_data.temperature_cold_yellow,
            temperature_cold_green=default_data.temperature_cold_green,
            temperature_hot_red=default_data.temperature_hot_red,
            temperature_hot_yellow=default_data.temperature_hot_yellow,
            temperature_hot_green=default_data.temperature_hot_green,
            revision_history='',
            created_at=default_data.created_at,
            updated_at=default_data.updated_at,
        )
    
    # 迁移所有机场信息到新的机场信息表
    for airport in AirportInfoAndAlertThresholds.objects.all():
        AirportInfo.objects.create(
            airport_4code=airport.airport_4code,
            airport_3code=airport.airport_3code,
            airport_name=airport.airport_name,
            classification=airport.classification,
            area=airport.area,
            area_code=airport.area_code,
            forecast_phone=airport.forecast_phone,
            observation_phone=airport.observation_phone,
            other_phone=airport.other_phone,
            extraInfo1=airport.extraInfo1,
            extraInfo2=airport.extraInfo2,
            extraInfo3=airport.extraInfo3,
            extraInfo4=airport.extraInfo4,
            extraInfo5=airport.extraInfo5,
            extraInfo6=airport.extraInfo6,
            revision_history='',
            created_at=airport.created_at,
            updated_at=airport.updated_at,
        )


def migrate_data_reverse(apps, schema_editor):
    """回滚数据迁移"""
    # 由于我们会在后续步骤中删除原表，这里只是清空新表
    AirportInfo = apps.get_model('core', 'AirportInfo')
    AirportAlertThresholds = apps.get_model('core', 'AirportAlertThresholds')
    AirportInfo.objects.all().delete()
    AirportAlertThresholds.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_airportinfoandalertthresholds_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportAlertThresholds',
            fields=[
                ('airport_4code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='机场四字代码')),
                ('visibility_m_red', models.PositiveIntegerField(default=800, verbose_name='能见度红色告警值')),
                ('visibility_m_yellow', models.PositiveIntegerField(default=1600, verbose_name='能见度黄色告警值')),
                ('visibility_m_green', models.PositiveIntegerField(default=2000, verbose_name='能见度绿色告警值')),
                ('cloud_min_red', models.PositiveIntegerField(default=2, verbose_name='云高红色告警值')),
                ('cloud_min_yellow', models.PositiveIntegerField(default=5, verbose_name='云高黄色告警值')),
                ('cloud_min_green', models.PositiveIntegerField(default=10, verbose_name='云高绿色告警值')),
                ('average_wind_speed_mps_red', models.PositiveIntegerField(default=12, verbose_name='平均风红色告警值')),
                ('average_wind_speed_mps_yellow', models.PositiveIntegerField(default=8, verbose_name='平均风黄色告警值')),
                ('average_wind_speed_mps_green', models.PositiveIntegerField(default=5, verbose_name='平均风绿色告警值')),
                ('gust_mps_red', models.PositiveIntegerField(default=17, verbose_name='阵风红色告警值')),
                ('gust_mps_yellow', models.PositiveIntegerField(default=13, verbose_name='阵风黄色告警值')),
                ('gust_mps_green', models.PositiveIntegerField(default=10, verbose_name='阵风绿色告警值')),
                ('temperature_cold_red', models.IntegerField(default=-30, verbose_name='低温红色告警值')),
                ('temperature_cold_yellow', models.IntegerField(default=-27, verbose_name='低温黄色告警值')),
                ('temperature_cold_green', models.IntegerField(default=-25, verbose_name='低温绿色告警值')),
                ('temperature_hot_red', models.PositiveIntegerField(default=40, verbose_name='高温红色告警值')),
                ('temperature_hot_yellow', models.PositiveIntegerField(default=37, verbose_name='高温黄色告警值')),
                ('temperature_hot_green', models.PositiveIntegerField(default=35, verbose_name='高温绿色告警值')),
                ('revision_history', models.TextField(blank=True, null=True, verbose_name='修订历史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机场告警阈值',
                'verbose_name_plural': '机场告警阈值',
                'db_table': 'airport_alert_thresholds',
            },
        ),
        migrations.CreateModel(
            name='AirportInfo',
            fields=[
                ('airport_4code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='机场四字代码')),
                ('airport_3code', models.CharField(blank=True, max_length=3, null=True, verbose_name='机场三字代码')),
                ('airport_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='机场名称')),
                ('classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='性质')),
                ('area', models.CharField(blank=True, choices=[('华中', '华中'), ('华南', '华南'), ('华东', '华东'), ('华北', '华北'), ('东北', '东北'), ('西南', '西南'), ('西北', '西北'), ('港台', '港台'), ('其它', '其它'), ('东亚', '东亚'), ('东南亚', '东南亚'), ('南亚', '南亚'), ('中东', '中东'), ('中/西亚', '中/西亚'), ('欧洲', '欧洲'), ('北美', '北美'), ('南美', '南美'), ('澳洲', '澳洲'), ('非洲', '非洲')], max_length=10, null=True, verbose_name='区域')),
                ('area_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='区号')),
                ('forecast_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='预报电话')),
                ('observation_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='观测电话')),
                ('other_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='其他电话')),
                ('extraInfo1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('extraInfo2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('extraInfo3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('extraInfo4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('extraInfo5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('extraInfo6', models.TextField(blank=True, null=True, verbose_name='预留字段6')),
                ('revision_history', models.TextField(blank=True, null=True, verbose_name='修订历史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机场信息',
                'verbose_name_plural': '机场信息',
                'db_table': 'airport_info',
            },
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_reverse),
    ]
