# Generated by Django 5.2.4 on 2025-09-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_split_airport_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirportInfoAndAlertThresholds',
        ),
    ]
