# Generated by Django 5.2.4 on 2025-09-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_old_airport_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalClassification',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('domestic_region', models.CharField(blank=True, max_length=20, null=True, verbose_name='国内区域')),
                ('international_region', models.CharField(blank=True, max_length=20, null=True, verbose_name='国际区域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '区域分类',
                'verbose_name_plural': '区域分类',
                'db_table': 'regional_classification',
                'ordering': ['id'],
            },
        ),
    ]
