# Generated by Django 5.2.4 on 2025-09-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_regional_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=12, verbose_name='用户代码')),
                ('access_time', models.DateTimeField(verbose_name='访问时间')),
                ('access_api', models.CharField(help_text='A:航班API, B:历史报文API, C:METAR API, D:TAF API', max_length=1, verbose_name='访问API')),
            ],
            options={
                'verbose_name': '用户访问日志',
                'verbose_name_plural': '用户访问日志',
                'db_table': 'user_access_logs',
                'ordering': ['-access_time'],
            },
        ),
        migrations.DeleteModel(
            name='RegionalClassification',
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['access_time'], name='user_access_access__d32a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccesslog',
            index=models.Index(fields=['user_code'], name='user_access_user_co_7c772b_idx'),
        ),
    ]
