# Generated by Django 5.2.4 on 2025-09-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_useraccesslog_delete_regionalclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=10, verbose_name='分类')),
                ('sequence', models.PositiveIntegerField(verbose_name='排序')),
                ('area', models.CharField(max_length=20, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '区域选项',
                'verbose_name_plural': '区域选项',
                'db_table': 'area_options',
                'ordering': ['classification', 'sequence'],
            },
        ),
    ]
