# Generated by Django 5.2.4 on 2025-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_areaoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportinfo',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='区域'),
        ),
    ]
