# Generated by Django 5.2.4 on 2025-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_area_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRefreshTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(choices=[('metar', '实况数据'), ('taf', '预报数据'), ('flight', '航班数据')], max_length=10, unique=True, verbose_name='数据类型')),
                ('init_time', models.FloatField(help_text='支持小数，如2.5表示2分30秒', verbose_name='起始时间(分钟)')),
                ('interval', models.FloatField(help_text='支持小数，如2.5表示每2分30秒更新一次', verbose_name='更新间隔(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据刷新定时器配置',
                'verbose_name_plural': '数据刷新定时器配置',
                'db_table': 'data_refresh_timer',
            },
        ),
    ]
