# Generated by Django 6.0.4 on 2026-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_qita_area_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarefreshtimer',
            name='data',
            field=models.CharField(choices=[('metar', '实况数据'), ('taf', '预报数据'), ('flight', '航班数据'), ('aircraft_parking', '停场数据')], max_length=20, unique=True, verbose_name='数据类型'),
        ),
    ]
